# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data_for_development:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: just4development
      MYSQL_DATABASE: stock
      MYSQL_USER: developer_user
      MYSQL_PASSWORD: developer_pass
      MYSQL_ROOT_HOST: 192.168.0.56/255.255.255.240
    ports:
      - 6603:3306
    networks:
      network:
        ipv4_address: 172.20.0.2

networks:
  network: 
    ipam:
      config:
        - subnet: 172.20.0.0/16
    
